name: Post-Process Test

on:
  push:
    branches:
      - main
    paths:
      - 'resources/**'
      - 'ui/raidboss/**'
      - 'ui/oopsyraidsy/**'
      - 'util/**'
      - '.github/workflows/post-process.yml'
      - '.github/actions/setup-js-env/'
  pull_request:
    paths:
      - 'resources/**'
      - 'ui/raidboss/**'
      - 'ui/oopsyraidsy/**'
      - 'util/**'
      - '.github/workflows/post-process.yml'
      - '.github/actions/setup-js-env/'

jobs:
  postprocess:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-js-env

      - name: npm run coverage-report
        run: |
          npm run coverage-report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: npm run process-triggers
        run: |
          npm run process-triggers
